declare
 valor NUMBER :=0;
 MAX_TABLE NUMBER:= 0;
 begin
    
 SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_REFERENCIAS';
 IF (VALOR =  0) THEN
    SELECT MAX(REF_CODIGO) INTO MAX_TABLE FROM DB_FABRICA.INV_REFERENCIAS;
     MAX_TABLE := MAX_TABLE + 1;
    EXECUTE IMMEDIATE  'CREATE SEQUENCE DB_FABRICA.SEQ_REFERENCIAS START WITH ' || MAX_TABLE || ' increment  by 1 NOCACHE NOCYCLE '; 
   -- DBMS_OUTPUT. put_line('CREATE SEQUENCE DB_FABRICA.SEQ_REFERENCIAS START WITH ' || MAX_TABLE || ' increment by 1');
    VALOR := 0;
    MAX_TABLE :=0;
 END IF;
 
 
  SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_COLORES';
 IF (VALOR =  0) THEN
     SELECT MAX(COLOR_CODIGO) INTO MAX_TABLE FROM DB_FABRICA.INV_COLORES;
     MAX_TABLE := MAX_TABLE + 1;
   EXECUTE IMMEDIATE  'CREATE SEQUENCE DB_FABRICA.SEQ_COLORES START WITH ' || MAX_TABLE || ' increment  by 1 NOCACHE NOCYCLE '; 
    VALOR := 0;
    MAX_TABLE :=0;
 END IF;
 
   SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TALLAS';
 IF (VALOR =  0) THEN
    SELECT MAX(TALLA_CODIGO) INTO MAX_TABLE FROM DB_FABRICA.INV_TALLAS;
     MAX_TABLE := MAX_TABLE + 1;
   EXECUTE IMMEDIATE  'CREATE SEQUENCE DB_FABRICA.SEQ_TALLAS START WITH ' || MAX_TABLE || ' increment  by 1 NOCACHE NOCYCLE '; 
    VALOR := 0;
    MAX_TABLE :=0;
 END IF;
 
    SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_INVENTARIO';
 IF (VALOR =  0) THEN
    SELECT MAX(INVENTARIO_CODIGO) INTO MAX_TABLE FROM DB_FABRICA.INV_INVENTARIO;
     MAX_TABLE := MAX_TABLE + 1;
   EXECUTE IMMEDIATE  'CREATE SEQUENCE DB_FABRICA.SEQ_INVENTARIO START WITH ' || MAX_TABLE || ' increment  by 1 NOCACHE NOCYCLE ';  
    VALOR := 0;
    MAX_TABLE :=0;
 END IF;
 
     SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TIPIDEN';
 IF (VALOR =  0) THEN
    SELECT MAX(TIPIDEN_CODIGO) INTO MAX_TABLE FROM DB_FABRICA.INV_TIPIDEN;
     MAX_TABLE := MAX_TABLE + 1;
   EXECUTE IMMEDIATE  'CREATE SEQUENCE DB_FABRICA.SEQ_TIPIDEN START WITH ' || MAX_TABLE || ' increment  by 1 NOCACHE NOCYCLE ';  
    VALOR := 0;
    MAX_TABLE :=0;
 END IF;
 
      SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_VENDEDOR';
 IF (VALOR =  0) THEN
    SELECT MAX(VENDEDOR_CODIGO) INTO MAX_TABLE FROM DB_FABRICA.INV_VENDEDORES;
     MAX_TABLE := MAX_TABLE + 1;
   EXECUTE IMMEDIATE  'CREATE SEQUENCE DB_FABRICA.SEQ_VENDEDOR START WITH ' || MAX_TABLE || ' increment  by 1 NOCACHE NOCYCLE ';  
    VALOR := 0;
    MAX_TABLE :=0;
 END IF;
 
 
/*
  SELECT last_number
  FROM user_sequences
 WHERE sequence_name = 'SEQ_REFERENCIAS';

 SELECT * FROM DB_FABRICA.INV_REFERENCIAS order by ref_codigo
 */
 
 end;
 
 
 
