/*
AUTOR: DAVID RODRIGUEZ RIVERA
FECHA: 21/02/2021
DESC:  ELIMINA todo lo creado para el esquema DB_FABRICA 
*/

DECLARE 
VALOR NUMBER; 
MY_USER VARCHAR2(30) := 'DB_FABRICA'; 

BEGIN 
  /*
-- DROP USER DB_FABRICA
SELECT COUNT(*) INTO VALOR FROM ALL_USERS WHERE USERNAME = MY_USER;
IF  (VALOR <> 0 ) THEN 
  EXECUTE IMMEDIATE 'DROP USER ' || MY_USER || ' CASCADE' ;
  DBMS_OUTPUT.put_line ('USUARIO: ' || MY_USER || ' ELIMINADO EXISTOSAMENTE!');
  ELSE
  DBMS_OUTPUT.put_line ('USUARIO: ' || MY_USER || ' NO EXISTE!');  
 END IF;
*/


-- ELIMINACION DE SEQUENCIAS



 SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_REFERENCIAS';
 IF (VALOR <>  0) THEN
     EXECUTE IMMEDIATE    'DROP SEQUENCE  DB_FABRICA.SEQ_REFERENCIAS' ; 
 END IF;
   
  SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_COLORES';
 IF (VALOR <>  0) THEN
   EXECUTE IMMEDIATE  'DROP SEQUENCE DB_FABRICA.SEQ_COLORES' ; 
     
 END IF;
 
   SELECT COUNT(*) INTO VALOR FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TALLAS';
 IF (VALOR <>  0) THEN
  EXECUTE IMMEDIATE   'DROP SEQUENCE DB_FABRICA.SEQ_TALLAS'; 
     
 END IF;
  

-- DROP TABLE INV_VENDEDORES

  SELECT COUNT (*) INTO VALOR FROM ALL_TABLES WHERE TABLE_NAME = 'INV_VENDEDORES' AND OWNER = 'DB_FABRICA';
  
  IF (VALOR <> 0) THEN 
  EXECUTE IMMEDIATE 'DROP TABLE DB_FABRICA.INV_VENDEDORES';
  END IF;


-- DROP TABLE INV_tipiden

  SELECT COUNT (*) INTO VALOR FROM ALL_TABLES WHERE TABLE_NAME = 'INV_TIPIDEN' AND OWNER = 'DB_FABRICA';
  
  IF (VALOR <> 0) THEN 
  EXECUTE IMMEDIATE 'DROP TABLE DB_FABRICA.INV_TIPIDEN';
  END IF;

-- DROP TABLE INV_INVENTARIO

  SELECT COUNT (*) INTO VALOR FROM ALL_TABLES WHERE TABLE_NAME = 'INV_INVENTARIO' AND OWNER = 'DB_FABRICA';
  
  IF (VALOR <> 0) THEN 
  EXECUTE IMMEDIATE 'DROP TABLE DB_FABRICA.INV_INVENTARIO';
  
  END IF;
-- DROP TABLE INV_REFERENCIAS

  SELECT COUNT (*) INTO VALOR FROM ALL_TABLES WHERE TABLE_NAME = 'INV_REFERENCIAS' AND OWNER = 'DB_FABRICA';
  
  IF (VALOR <> 0) THEN 
  EXECUTE IMMEDIATE 'DROP TABLE DB_FABRICA.INV_REFERENCIAS';
  
  END IF;
  
-- DROP TABLE INV_TALLAS

  SELECT COUNT (*) INTO VALOR FROM ALL_TABLES WHERE TABLE_NAME = 'INV_TALLAS' AND OWNER = 'DB_FABRICA';
  
  IF (VALOR <> 0) THEN 
  EXECUTE IMMEDIATE 'DROP TABLE DB_FABRICA.INV_TALLAS';
  
  END IF;
-- DROP TABLE INV_COLORES

  SELECT COUNT (*) INTO VALOR FROM ALL_TABLES WHERE TABLE_NAME = 'INV_COLORES' AND OWNER = 'DB_FABRICA';
  
  IF (VALOR <> 0) THEN 
  EXECUTE IMMEDIATE 'DROP TABLE DB_FABRICA.INV_COLORES';
  
  END IF;





END;
/  
